Table user {
  id int [pk, increment]
  name string [not null]
  first_name string [not null]
  surname string
  phone_number string
  email string
  username string [not null]
  password string
}

Table role {
  id int [pk, increment]
  name string [not null]
}

Table permission {
  id int [pk, increment]
}

Table user_role {
  id int [pk, increment]
  user_id int [not null, ref: > user.id]
  role_id int [not null, ref: > role.id]
}

Table role_permission {
  id int [pk, increment]
  role_id int [not null, ref: > role.id]
  permission_id int [not null, ref: > permission.id]
}

Table collaborator {
  id int [pk, increment]
  name string [not null]
  address string [not null]
  locality int [not null, ref: > locality.id]
}

Table collaborator_role {
  id int [pk, increment]
  user_id int [not null, ref: > user.id]
  collaborator_participation_id int [not null, ref: > collaborator_participation.id]
  role int [not null, ref: > role.id]
}

Table contact {
  id int [pk, increment]
  collaborator_id int [not null, ref: > collaborator.id]
  name string [not null]
  email string
  phone_number string
}

Table locality {
  id int [pk, increment]
  name string [not null]
  postal_code string [not null]
}

Table collaborator_participation {
  id int [pk, increment]
  collaborator_id int [not null, ref: > collaborator.id]
  campaign_id int [not null, ref: > campaign.id]
}

Table campaign_type {
  id int [pk, increment]
  name string [not null]
}

Table campaign {
  id int [pk, increment]
  campaign_type_id int [not null, ref: > campaign_type.id]
  name string [not null]
  start_date date [not null]
  end_date date [not null]
}

Table report_type {
  id int [pk, increment]
  name string [not null, unique]
}

Table report {
  id int [pk, increment]
  creation_date date [not null]
  resolution_date date [not null]
  description string [not null]
  solution string

  solved_by int [ref: > user.id]
  reported_by int [not null, ref: > user.id]
  campaign_id int [ref: > campaign.id]
  report_type_id int [not null, ref: > report_type.id]
}

Table store_role {
  id int [pk, increment]
  user_id int [not null, ref: > user.id]
  store_participation_id int [not null, ref: > store_participation.id]
  role int [not null, ref: > role.id]
}

Table store {
  id int [pk, increment]
  locality_id int [not null, ref: > locality.id]
  chain_id int [not null, ref: > chain.id]
  name string [not null, unique]
  address string [not null]
  checkout_shelfs integer [not null]
  zone_id int [ref: < zone.id]
}

Table chain {
  id int [pk, increment]
  code string [not null, unique]
}

Table store_participation {
  id int [pk, increment]
  store_id int [not null, ref: > store.id]
  campaign_id int [not null, ref: > campaign.id]
  participates bool [not null]

  indexes {
    (store_id, campaign_id) [unique]
  }
}

Table schedule {
  id int [pk, increment]
  store_id int [not null, ref: > store.id]
  week_day int [not null]
  opening_time time
  closing_time time
}

Table schedule_exception {
  id int [pk, increment]
  store_id int [not null, ref: > store.id]
  date date [not null]
  opening_time time
  closing_time time
  closed bool [not null]
}

Table shift {
  id int [pk, increment]
  date date [not null]
  start_time time [not null]
  end_time time [not null]
  notes string

  store_participation_id int [not null, ref: > store_participation.id]
}

Table volunteer_participation {
  id int [pk, increment]

  collaborator_participation_id int [not null, ref: > collaborator_participation.id]
  user_id int [not null, ref: > user.id]

  indexes {
    (user_id, collaborator_participation_id) [unique]
  }
}

Table shift_assignment {
  id int [pk, increment]
  shift_id int [not null, ref: > shift.id]

  volunteer_participation_id int [not null, ref: > volunteer_participation.id]

  indexes {
    (shift_id, volunteer_participation_id) [unique]
  }
}

Table zone {
  id int [pk, increment]
  name string [not null, unique]
  code string [not null]
}

Table zone_assignment {
  id int [pk, increment]
  campaign_id int [not null, ref: > campaign.id]
  zone_id int [not null, ref: > zone.id]
  user_id int [not null, ref: > user.id]

  indexes {
    (campaign_id, zone_id, user_id) [unique]
  }
}