FROM eclipse-temurin:25-jdk

WORKDIR /workspace

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl xz-utils ca-certificates \
    && curl -fsSL \
    https://github.com/watchexec/watchexec/releases/download/v2.5.1/watchexec-2.5.1-x86_64-unknown-linux-musl.tar.xz \
    -o /tmp/watchexec.tar.xz \
    && mkdir -p /tmp/watchexec \
    && tar -xJf /tmp/watchexec.tar.xz -C /tmp/watchexec --strip-components=1 \
    && install -m 0755 /tmp/watchexec/watchexec /usr/local/bin/watchexec \
    && watchexec --version \
    && rm -rf /tmp/watchexec /tmp/watchexec.tar.xz /var/lib/apt/lists/*

COPY . .

RUN chmod +x mvnw watcher.sh \
    && ./mvnw dependency:go-offline

CMD ["bash","./watcher.sh"]
